use plugin_registry::PluginRegistry;
use runtime_core::EventEnvelope;
use serde_json::json;
use station_schema::{SchemaError, SchemaRegistry};
use station_supervisor::{PluginRuntimeState, StationSupervisor};

#[derive(Debug, thiserror::Error)]
pub enum PolicyError {
    #[error("schema error: {0}")]
    Schema(#[from] SchemaError),
}

#[derive(Debug, Clone)]
pub struct EventAdmission {
    pub allowed: bool,
    pub reason: Option<String>,
    pub policy_event: Option<EventEnvelope>,
}

impl EventAdmission {
    pub fn allowed(policy_event: EventEnvelope) -> Self {
        Self {
            allowed: true,
            reason: None,
            policy_event: Some(policy_event),
        }
    }

    pub fn denied(reason: impl Into<String>, policy_event: EventEnvelope) -> Self {
        Self {
            allowed: false,
            reason: Some(reason.into()),
            policy_event: Some(policy_event),
        }
    }

    pub fn assert_allowed(&self) {
        assert!(
            self.allowed,
            "event denied: {}",
            self.reason.as_deref().unwrap_or("unknown policy reason")
        );
    }
}

pub struct PolicyEngine<'a> {
    pub plugins: &'a PluginRegistry,
    pub schemas: &'a SchemaRegistry,
    pub supervisor: &'a StationSupervisor,
}

impl<'a> PolicyEngine<'a> {
    /// Admit a plugin-originating event through policy checks.
    ///
    /// # Policy Checks
    ///
    /// 1. Source plugin must be registered
    /// 2. Source plugin must be authorized to publish the topic
    /// 3. Source plugin must be in an admitted or running state
    /// 4. Schema must exist for the topic
    /// 5. Schema hash must be attached (auto-attached if missing)
    /// 6. Payload must validate against the schema
    ///
    /// # System Events
    ///
    /// System-originating events (policy.event.*, supervisor.*) bypass this admission
    /// process. They are replayable control-plane evidence generated by the kernel
    /// itself and do not require plugin policy admission or schema validation.
    fn create_policy_event(
        &self,
        event: &EventEnvelope,
        allowed: bool,
        reason: Option<&str>,
    ) -> EventEnvelope {
        let topic = if allowed {
            "policy.event.admitted"
        } else {
            "policy.event.denied"
        };

        let mut payload = json!({
            "source": event.source.clone(),
            "topic": event.topic.clone(),
            "event_id": event.event_id.clone(),
            "trace_id": event.trace_id.clone(),
        });

        if let Some(reason) = reason {
            payload["reason"] = json!(reason);
        }

        EventEnvelope::child_of(
            event,
            topic,
            "station_policy",
            payload,
        )
    }

    pub fn admit_event(&self, event: &mut EventEnvelope) -> Result<EventAdmission, PolicyError> {
        // 1. Source plugin must be registered.
        if !self.plugins.has_plugin(&event.source) {
            let reason = format!("plugin not registered: {}", event.source);
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        }

        // 2. Source plugin must be allowed to publish event.topic.
        if !self.plugins.can_publish(&event.source, &event.topic) {
            let reason = format!("plugin {} cannot publish topic {}", event.source, event.topic);
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        }

        // 3. Source plugin must be Admitted or Running.
        let Some(state) = self.supervisor.state_of(&event.source) else {
            let reason = format!("plugin {} missing from supervisor runtime", event.source);
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        };

        if state != PluginRuntimeState::Admitted && state != PluginRuntimeState::Running {
            let reason = format!("plugin {} not in publishable state: {state:?}", event.source);
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        }

        // 4. Schema must exist.
        if self.schemas.schema_for_topic(&event.topic).is_none() {
            let reason = format!("missing schema for topic {}", event.topic);
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        }

        // 5. Attach schema hash if missing.
        if event.schema_hash.is_none() {
            if let Err(err) = self.schemas.attach_schema_hash(event) {
                let reason = format!("schema hash attachment failed: {err}");
                let policy_event = self.create_policy_event(event, false, Some(&reason));
                return Ok(EventAdmission::denied(reason, policy_event));
            }
        }

        // 6. Validate payload.
        if let Err(err) = self.schemas.validate(event) {
            let reason = format!("schema validation failed: {err}");
            let policy_event = self.create_policy_event(event, false, Some(&reason));
            return Ok(EventAdmission::denied(reason, policy_event));
        }

        // 7. Create admission policy event and return allowed.
        let policy_event = self.create_policy_event(event, true, None);
        Ok(EventAdmission::allowed(policy_event))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use plugin_registry::{PluginKind, PluginManifest, TransportKind};
    use serde_json::json;
    use station_schema::{FieldType, PayloadSchema};

    fn manifest() -> PluginManifest {
        PluginManifest {
            id: "adapter_quantum".to_string(),
            kind: PluginKind::Compute,
            transport: TransportKind::Local,
            version: "0.1.0".to_string(),
            artifact_hash:
                "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
                    .to_string(),
            subscribes: vec!["quantum.analyze".to_string()],
            publishes: vec!["quantum.state".to_string()],
            capabilities: vec!["collapse_ratio".to_string()],
        }
    }

    fn schema() -> PayloadSchema {
        PayloadSchema::new("tnsr.quantum.state.v1", "quantum.state", "1")
            .required("state_dim", FieldType::Integer)
            .required("collapse_ratio", FieldType::Number)
            .required("euler_characteristic", FieldType::Integer)
            .build()
    }

    #[test]
    fn admits_valid_event_and_attaches_schema_hash() {
        let manifest = manifest();

        let mut registry = PluginRegistry::default();
        registry
            .register(manifest.clone())
            .expect("register plugin");

        let mut supervisor = StationSupervisor::new("default");
        supervisor
            .register_plugin(&manifest)
            .expect("supervisor register plugin");
        supervisor
            .transition(&manifest.id, PluginRuntimeState::Admitted)
            .expect("admit plugin");

        let mut schemas = SchemaRegistry::default();
        schemas.register(schema()).expect("register schema");

        let mut event = EventEnvelope::new(
            supervisor.session.run_id.clone(),
            "quantum.state",
            "adapter_quantum",
            json!({
                "state_dim": 16,
                "collapse_ratio": 0.42,
                "euler_characteristic": 8
            }),
        );

        let admission = PolicyEngine {
            plugins: &registry,
            schemas: &schemas,
            supervisor: &supervisor,
        }
        .admit_event(&mut event)
        .expect("admission should not error");

        assert!(admission.allowed);
        assert!(event.schema_hash.is_some());

        // Verify policy event was created
        let policy_event = admission.policy_event.expect("policy event should exist");
        assert_eq!(policy_event.topic, "policy.event.admitted");
        assert_eq!(policy_event.source, "station_policy");
        assert_eq!(policy_event.trace_id, event.trace_id);
        assert_eq!(policy_event.parent_id.as_ref(), Some(&event.event_id));
    }

    #[test]
    fn denies_unregistered_plugin() {
        let supervisor = StationSupervisor::new("default");
        let schemas = SchemaRegistry::default();
        let registry = PluginRegistry::default();
        let mut event = EventEnvelope::new(
            "run-test",
            "quantum.state",
            "unknown_plugin",
            json!({ "state_dim": 16 }),
        );

        let admission = PolicyEngine {
            plugins: &registry,
            schemas: &schemas,
            supervisor: &supervisor,
        }
        .admit_event(&mut event)
        .expect("admission should not error");

        assert!(!admission.allowed);
        assert!(admission
            .reason
            .expect("denial reason")
            .contains("not registered"));

        // Verify policy event was created
        let policy_event = admission.policy_event.expect("policy event should exist");
        assert_eq!(policy_event.topic, "policy.event.denied");
        assert_eq!(policy_event.source, "station_policy");
        assert_eq!(policy_event.trace_id, event.trace_id);
        assert_eq!(policy_event.parent_id.as_ref(), Some(&event.event_id));

        // Verify denial includes required fields
        let payload = &policy_event.payload;
        assert_eq!(payload["source"], "unknown_plugin");
        assert_eq!(payload["topic"], "quantum.state");
        assert!(payload["reason"].as_str().unwrap().contains("not registered"));
    }

    #[test]
    fn policy_events_are_replayable_on_denial() {
        use station_replay::JsonlReplayLog;

        let temp_dir = std::env::temp_dir();
        let run_id = format!("run-test-{}", ulid::Ulid::new());
        let events_path = temp_dir.join(format!("{}-events.jsonl", run_id));

        let supervisor = StationSupervisor::new("default");
        let schemas = SchemaRegistry::default();
        let registry = PluginRegistry::default();

        let mut event = EventEnvelope::new(
            &run_id,
            "quantum.state",
            "unknown_plugin",
            json!({ "state_dim": 16 }),
        );

        let policy = PolicyEngine {
            plugins: &registry,
            schemas: &schemas,
            supervisor: &supervisor,
        };

        let admission = policy.admit_event(&mut event).expect("policy check");

        assert!(!admission.allowed);

        // Write policy denial to replay
        let mut replay = JsonlReplayLog::open(&events_path).expect("open replay");
        if let Some(policy_event) = admission.policy_event {
            replay.append(&policy_event).expect("append policy event");
        }

        // Verify replay contains the denial
        let events = JsonlReplayLog::read_all(&events_path).expect("read replay");
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].topic, "policy.event.denied");
        assert_eq!(events[0].source, "station_policy");

        // Verify replay chain is valid
        let report = JsonlReplayLog::verify_chain(&events_path).expect("verify chain");
        assert_eq!(report.records_verified, 1);

        let _ = std::fs::remove_file(events_path);
    }
}
